### ISSUE TITLE
[Bug] Crashes when opening image in SMS app

### ISSUE THREAD

**Issue by pvxcooper** [IacobIonut01/Gallery#113]
The app crashes when I click to open an image in my messaging app. Here is my crash log:

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230705.001/2023071100:user/release-keys
package: com.dot.gallery:11065
process: com.dot.gallery
processUptime: 70967 + 189 ms

java.lang.NullPointerException
	at k9.l.a(Unknown Source:22)
	at b0.a1.q1(Unknown Source:782)
	at b0.a1.l0(Unknown Source:20)
	at e7.g.j(Unknown Source:598)
	at com.bumptech.glide.e.r(Unknown Source:1326)
	at y8.f.Y(Unknown Source:32)
	at k0.z.K(Unknown Source:283)
	at p.c2.a(Unknown Source:444)
	at p.c2.r(Unknown Source:49)
	at com.bumptech.glide.d.A0(Unknown Source:43)
	at k0.z.q(Unknown Source:128)
	at k0.z.I(Unknown Source:35)
	at k0.f0.u(Unknown Source:17)
	at k0.e2.o(Unknown Source:100)
	at t.q.l(Unknown Source:533)
	at androidx.compose.ui.platform.t0.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.r0.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: vb.f: [k0.o1@4c6fc0, androidx.compose.ui.platform.s1@91844f9, m1{Cancelling}@5ef6c3e, s0@fe02a9f]

```

**Comment by IacobIonut01** [comment]
Thanks for reporting, make sure to use the latest apk from the 'Actions' tab, if it's still crashing, lmk!

**Comment by IacobIonut01** [comment]
Is the issue fixed? If not re-open the issue

**Comment by pvxcooper** [comment]
Yes, the apk from actions fixed it.
