### ISSUE TITLE
[BUG] app crahes when opening any Album 

### ISSUE THREAD

**Issue by Stzyxh** [IacobIonut01/Gallery#563]
**Describe the bug**
When i open it it instantly crashes

**To Reproduce**
1. Go to 'album page.'
2. Click on 'and album .'
3. See error

**Expected behavior**
App crahes

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: faiphone 4
 - OS: Android 13
 - Version: 3.1.1

**Additional context**

**Comment by IacobIonut01** [comment]
Can't reproduce, provide logs

**Comment by Stzyxh** [comment]
> Can't reproduce, provide logs

uhhh. I have logcat but it there are no logs about the crash. Is there another way to to it.

**Comment by IacobIonut01** [comment]
search for "FATAL"

**Comment by Stzyxh** [comment]
> search for "FATAL"

ust forgot shizuku Heres the crashlog

**FATAL EXCEPTION: main
Process: com.dot.gallery, PID: 22324
java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..16)
	at android.graphics.ColorSpace.get(ColorSpace.java:1390)
	at android.graphics.Color.colorSpace(Color.java:703)
	at android.graphics.Shader.detectColorSpace(Shader.java:238)
	at android.graphics.LinearGradient.<init>(LinearGradient.java:94)
	at x0.L.a(Unknown Source:44)
	at x0.i0.a(Unknown Source:67)
	at u7.i.f(Unknown Source:120)
	at O0.N.b(Unknown Source:49)
	at O0.t0.T0(Unknown Source:52)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.N.a(Unknown Source:174)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemAnimator$a.f(Unknown Source:98)
	at O0.N.b(Unknown Source:49)
	at O0.t0.T0(Unknown Source:52)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.N.a(Unknown Source:174)
	at androidx.compose.foundation.f.f(Unknown Source:159)
	at O0.N.b(Unknown Source:49)
	at O0.t0.T0(Unknown Source:52)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.F.o1(Unknown Source:5)
	at O0.N.a(Unknown Source:174)
	at androidx.compose.foundation.f.f(Unknown Source:159)
	at O0.N.b(Unknown Source:49)
	at O0.t0.T0(Unknown Source:52)
	at O0.t0.S0(Unknown Source:27)
	at O0.F.o1(Unknown Source:5)
	at O0.t0.T0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:113)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:127)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:73)
	at A0.f.g(Unknown Source:82)
	at A0.f.f(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.S0(Unknown Source:4)
	at O0.J.j(Unknown Source:4)
	at O0.z.o1(Unknown Source:27)
	at O0.t0.T0(Unknown Source:8)
	at O0.t0.S0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at androidx.compose.ui.platform.a.dispatchDraw(Unknown Source:39)
	at android.view.View.draw(View.java:23208)
	at android.view.View.updateDisplayListIfDirty(View.java:22072)
	at android.view.View.draw(View.java:22936)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22063)
	at android.view.View.draw(View.java:22936)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22063)
	at android.view.View.draw(View.java:22936)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22063)
	at android.view.View.draw(View.java:22936)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22063)
	at android.view.View.draw(View.java:22936)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22063)
	at android.view.View.draw(View.java:22936)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23208)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.View.updateDisplayListIfDirty(View.java:22072)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4384)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2331)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9090)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
	at android.view.Choreographer.doFrame(Choreographer.java:916)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7932)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)**

**Comment by Stzyxh** [comment]
Any updates? @IacobIonut01

**Comment by IacobIonut01** [comment]
I have been able to reproduce the issue. A fix will be available soon

**Comment by Stzyxh** [comment]
Still crashes
 FATAL EXCEPTION: main
Process: com.dot.gallery, PID: 4864
java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..16)
	at android.graphics.ColorSpace.get(ColorSpace.java:1390)
	at android.graphics.Color.colorSpace(Color.java:703)
	at android.graphics.Shader.detectColorSpace(Shader.java:238)
	at android.graphics.LinearGradient.<init>(LinearGradient.java:94)
	at x0.L.a(Unknown Source:44)
	at x0.i0.a(Unknown Source:67)
	at u7.i.f(Unknown Source:120)
	at O0.N.b(Unknown Source:49)
	at O0.t0.U0(Unknown Source:52)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.N.a(Unknown Source:174)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemAnimator$a.f(Unknown Source:84)
	at O0.N.b(Unknown Source:49)
	at O0.t0.U0(Unknown Source:52)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.N.a(Unknown Source:174)
	at androidx.compose.foundation.f.f(Unknown Source:159)
	at O0.N.b(Unknown Source:49)
	at O0.t0.U0(Unknown Source:52)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.J.j(Unknown Source:4)
	at O0.z.p1(Unknown Source:27)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.v0.c(Unknown Source:9)
	at o0.j$a.c(Unknown Source:55)
	at o0.H$a.a(Unknown Source:55)
	at o0.H.e(Unknown Source:120)
	at O0.T0.b(Unknown Source:2)
	at O0.u0.j(Unknown Source:34)
	at P0.n0.a(Unknown Source:22)
	at A0.c.a(Unknown Source:59)
	at A0.f.f(Unknown Source:82)
	at A0.f.e(Unknown Source:69)
	at P0.o0.j(Unknown Source:134)
	at P0.o0.g(Unknown Source:0)
	at O0.t0.T0(Unknown Source:4)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)
	at O0.F.p1(Unknown Source:5)
	at O0.t0.U0(Unknown Source:8)
	at O0.t0.T0(Unknown Source:27)

**Comment by Stzyxh** [comment]
It's fixed. Thanks for your work
